package pagerduty

import "time"

var gmtOffset = map[string]time.Duration{
	"Hawaii":                       -10 * time.Hour,
	"Alaska":                       -9 * time.Hour,
	"Pacific Time (US & Canada)":   -8 * time.Hour,
	"Arizona":                      -7 * time.Hour,
	"Mountain Time (US & Canada)":  -7 * time.Hour,
	"Central Time (US & Canada)":   -6 * time.Hour,
	"Eastern Time (US & Canada)":   -5 * time.Hour,
	"Indiana (East)":               -5 * time.Hour,
	"American Samoa":               -11 * time.Hour,
	"International Date Line West": -11 * time.Hour,
	"Midway Island":                -11 * time.Hour,
	"Tijuana":                      -8 * time.Hour,
	"Chihuahua":                    -7 * time.Hour,
	"Mazatlan":                     -7 * time.Hour,
	"Central America":              -6 * time.Hour,
	"Guadalajara":                  -6 * time.Hour,
	"Mexico City":                  -6 * time.Hour,
	"Monterrey":                    -6 * time.Hour,
	"Saskatchewan":                 -6 * time.Hour,
	"Bogota":                       -5 * time.Hour,
	"Lima":                         -5 * time.Hour,
	"Quito":                        -5 * time.Hour,
	"Caracas":                      -4*time.Hour + 30*time.Minute,
	"Atlantic Time (Canada)":       -4 * time.Hour,
	"Georgetown":                   -4 * time.Hour,
	"La Paz":                       -4 * time.Hour,
	"Santiago":                     -4 * time.Hour,
	"Newfoundland":                 -3*time.Hour + 30*time.Minute,
	"Brasilia":                     -3 * time.Hour,
	"Buenos Aires":                 -3 * time.Hour,
	"Greenland":                    -3 * time.Hour,
	"Mid-Atlantic":                 -2 * time.Hour,
	"Azores":                       -1 * time.Hour,
	"Cape Verde Is.":               -1 * time.Hour,
	"Casablanca":                   0 * time.Hour,
	"Dublin":                       0 * time.Hour,
	"Edinburgh":                    0 * time.Hour,
	"Lisbon":                       0 * time.Hour,
	"London":                       0 * time.Hour,
	"Monrovia":                     0 * time.Hour,
	"UTC":                          0 * time.Hour,
	"Amsterdam":                    1 * time.Hour,
	"Belgrade":                     1 * time.Hour,
	"Berlin":                       1 * time.Hour,
	"Bern":                         1 * time.Hour,
	"Bratislava":                   1 * time.Hour,
	"Brussels":                     1 * time.Hour,
	"Budapest":                     1 * time.Hour,
	"Copenhagen":                   1 * time.Hour,
	"Ljubljana":                    1 * time.Hour,
	"Madrid":                       1 * time.Hour,
	"Paris":                        1 * time.Hour,
	"Prague":                       1 * time.Hour,
	"Rome":                         1 * time.Hour,
	"Sarajevo":                     1 * time.Hour,
	"Skopje":                       1 * time.Hour,
	"Stockholm":                    1 * time.Hour,
	"Vienna":                       1 * time.Hour,
	"Warsaw":                       1 * time.Hour,
	"West Central Africa":          1 * time.Hour,
	"Zagreb":                       1 * time.Hour,
	"Athens":                       2 * time.Hour,
	"Bucharest":                    2 * time.Hour,
	"Cairo":                        2 * time.Hour,
	"Harare":                       2 * time.Hour,
	"Helsinki":                     2 * time.Hour,
	"Istanbul":                     2 * time.Hour,
	"Jerusalem":                    2 * time.Hour,
	"Kyiv":                         2 * time.Hour,
	"Pretoria":                     2 * time.Hour,
	"Riga":                         2 * time.Hour,
	"Sofia":                        2 * time.Hour,
	"Tallinn":                      2 * time.Hour,
	"Vilnius":                      2 * time.Hour,
	"Baghdad":                      3 * time.Hour,
	"Kuwait":                       3 * time.Hour,
	"Minsk":                        3 * time.Hour,
	"Nairobi":                      3 * time.Hour,
	"Riyadh":                       3 * time.Hour,
	"Tehran":                       3*time.Hour + 30*time.Minute,
	"Abu Dhabi":                    4 * time.Hour,
	"Baku":                         4 * time.Hour,
	"Moscow":                       4 * time.Hour,
	"Muscat":                       4 * time.Hour,
	"St. Petersburg":               4 * time.Hour,
	"Tbilisi":                      4 * time.Hour,
	"Volgograd":                    4 * time.Hour,
	"Yerevan":                      4 * time.Hour,
	"Kabul":                        4*time.Hour + 30*time.Minute,
	"Islamabad":                    5 * time.Hour,
	"Karachi":                      5 * time.Hour,
	"Tashkent":                     5 * time.Hour,
	"Chennai":                      5*time.Hour + 30*time.Minute,
	"Kolkata":                      5*time.Hour + 30*time.Minute,
	"Mumbai":                       5*time.Hour + 30*time.Minute,
	"New Delhi":                    5*time.Hour + 30*time.Minute,
	"Sri Jayawardenepura":          5*time.Hour + 30*time.Minute,
	"Kathmandu":                    5*time.Hour + 45*time.Minute,
	"Almaty":                       6 * time.Hour,
	"Astana":                       6 * time.Hour,
	"Dhaka":                        6 * time.Hour,
	"Ekaterinburg":                 6 * time.Hour,
	"Rangoon":                      6*time.Hour + 30*time.Minute,
	"Bangkok":                      7 * time.Hour,
	"Hanoi":                        7 * time.Hour,
	"Jakarta":                      7 * time.Hour,
	"Novosibirsk":                  7 * time.Hour,
	"Beijing":                      8 * time.Hour,
	"Chongqing":                    8 * time.Hour,
	"Hong Kong":                    8 * time.Hour,
	"Krasnoyarsk":                  8 * time.Hour,
	"Kuala Lumpur":                 8 * time.Hour,
	"Perth":                        8 * time.Hour,
	"Singapore":                    8 * time.Hour,
	"Taipei":                       8 * time.Hour,
	"Ulaan Bataar":                 8 * time.Hour,
	"Urumqi":                       8 * time.Hour,
	"Irkutsk":                      9 * time.Hour,
	"Osaka":                        9 * time.Hour,
	"Sapporo":                      9 * time.Hour,
	"Seoul":                        9 * time.Hour,
	"Tokyo":                        9 * time.Hour,
	"Adelaide":                     9*time.Hour + 30*time.Minute,
	"Darwin":                       9*time.Hour + 30*time.Minute,
	"Brisbane":                     10 * time.Hour,
	"Canberra":                     10 * time.Hour,
	"Guam":                         10 * time.Hour,
	"Hobart":                       10 * time.Hour,
	"Melbourne":                    10 * time.Hour,
	"Port Moresby":                 10 * time.Hour,
	"Sydney":                       10 * time.Hour,
	"Yakutsk":                      10 * time.Hour,
	"New Caledonia":                11 * time.Hour,
	"Vladivostok":                  11 * time.Hour,
	"Auckland":                     12 * time.Hour,
	"Fiji":                         12 * time.Hour,
	"Kamchatka":                    12 * time.Hour,
	"Magadan":                      12 * time.Hour,
	"Marshall Is.":                 12 * time.Hour,
	"Solomon Is.":                  12 * time.Hour,
	"Wellington":                   12 * time.Hour,
	"Nuku'alofa":                   13 * time.Hour,
	"Samoa":                        13 * time.Hour,
	"Tokelau Is.":                  13 * time.Hour,
}
